services:
  # 1. Your API Container
  api:
    build: .
    image: social-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db  # Tells Docker to wait for the database to start first

  # 2. Your New Database Container
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=sisco
      - POSTGRES_PASSWORD=sisco
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-data:/var/lib/postgresql/data # Saves your data so it isn't deleted when the container stops

# 3. Define the Volume for the database
volumes:
  postgres-data:
